### ISSUE TITLE
Results of training without meta learning

### ISSUE THREAD

**Issue by WentaoTan** [bismex/MetaBIN#10]
Hello. When I was reading your paper, I had a doubt: What would be the result if meta-learning was not used during training? So I went to study your code but didn't understand it. Could you please tell me the result without meta-learning or how to modify the code?

**Comment by bismex** [comment]
Thank you for your interest.

You can see this result is Table 3, Table 4, and Table 5, denoted by BN. The method specified as BN is a method of learning the existing BN-based backbone in multiple source domains without using meta-learning. Comparing the proposed MetaBIN method with the existing BN performance, there is a big performance difference with rank-1 accuracy of 65.7% and 50.9% in the large scale DG re-id benchmark. 

In order to operate the BN-based model without using meta-learning in the code, please refer to the code modifications below.
1) In this code (MetaBIN/configs/Sample/DG-mobilenet.yml), put "BN" instead of "BIN_gate2" for the variable in MODEL.NORM.TYPE_BACKBONE. This means using BN instead of batch-instance normalization. 
2) In this code (MetaBIN/configs/Base-DG.yml), put "" or '' (empty) instead of "DG" for the variable in META.DATA.NAMES. This means not using the meta-learning scheme. Instead of modifying this code (MetaBIN/configs/Base-DG.yml), you can add the META.DATA.NAMES variable in this code (MetaBIN/configs/Sample/DG-mobilenet.yml) and set the value to "" like this.

```
<DG-mobilenet.yml>
...

META:
  DATA:
    MTRAIN_MINI_BATCH: 80 
    MTRAIN_NUM_INSTANCE: 4
    MTEST_MINI_BATCH: 80 
    MTEST_NUM_INSTANCE: 4
    NAMES: "" # add this

...

MODEL:
  NORM:
    TYPE_BACKBONE: "BN" # change this

...

```


Please feel free to contact us if you have any questions.

Thanks, 
Seokeon Choi
